#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X


bspc config border_width         3
bspc config window_gap          0
bspc config normal_border_color "#3264a8"
bspc config focused_border_color "#ff9100"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
